<?php
$grape_variety_list = array(
array('Abouriou','Абуриу'),
array('Abovyani','Абовяни'),
array('Adzhi','Аджи'),
array('Agaraki','Агараки'),
array('Agarceni','Агарцени'),
array('Agavam','Агавам'),
array('Agbizh','Агбиж'),
array('Agiorgitiko','Агиоргитико'),
array('Aglianico','Альянико'),
array('Agostenga','Агостенга'),
array('Agria','Агриа'),
array('Agymastos','Агумастос'),
array('Aidani','Аидани'),
array('Airen','Айрен'),
array('Akabil','Акабил'),
array('Akabilizh','Акабилиж'),
array('Aladasturi','Аладастури'),
array('Alarije','Аларихе'),
array('Albalonga','Альбалонга'),
array('Albana','Альбана'),
array('Albanello','Альбанелло'),
array('Albarello','Альбарелло'),
array('Albarin Blanco','Альбарин Бланко'),
array('Albarino','Альбариньо'),
array('Albarola','Альбарола'),
array('Albarossa','Альбаросса'),
array('Albillo','Альбильо'),
array('Aleatico','Алеатико'),
array('Alexandreuli','Александроули'),
array('Alfrocheiro','Альфрокейро'),
array('Alibernet','Алиберне'),
array('Alicante Bouschet','Аликанте Буше'),
array('Aligote','Алиготе'),
array('Altesse','Альтесс'),
array('Alvarelhao','Альварельхао'),
array('Amigne','Амин'),
array('Ancellotta','Анчелотта'),
array('Ancellotta','Анчеллотта'),
array('Ansonica','Ансоника'),
array('Antao Vaz','Антау Важ'),
array('Aragonez','Арагонес'),
array('Aramon','Арамон'),
array('Arbane','Арбан'),
array('Areni','Арени'),
array('Argaman','Аргаман'),
array('Arinarnoa','Аринарноа'),
array('Arinto','Аринту'),
array('Arneis','Арнейс'),
array('Arneis','Арнеис'),
array('Arnsburger','Арнсбургер'),
array('Arrufiac','Арруфьяк'),
array('Arvisiniadu','Арвизиниаду'),
array('Aspiran','Аспиран'),
array('Assario Branco','Ассарио Бранко'),
array('Assyrtico','Ассиртико'),
array('Athiri','Атири'),
array('Aubun','Обэн'),
array('Auxerrois','Оксеруа'),
array('Avasirhva','Авасирхва'),
array('Avesso','Авессу'),
array('Avgoustiatis','Августьятис'),
array('Avgysta','Августа'),
array('Avrora','Аврора'),
array('Avshiluri','Авшилури'),
array('Azal Branco','Азаль Бранко'),
array('Azal Tinto','Азаль Тинто'),
array('Azateni','Азатени'),
array('Azhapsh','Ажапш'),
array('Babic','Бабич'),
array('Baboso Negro','Бабосо Негро'),
array('Bacchus','Бахус'),
array('Baco','Бако'),
array('Baga','Бага'),
array('Barbarossa','Барбаросса'),
array('Barbera','Барбера'),
array('Barbera del Sannio','Барбера дель Саннио'),
array('Baroque','Барок'),
array('Bastardo','Бастардо'),
array('Bastardo Magarachskiy','Бастардо Магарачский'),
array('Bayan Shirey','Баян Ширей'),
array('Bekari','Бекари'),
array('Bellone','Беллоне'),
array('Bianca','Бианка'),
array('Bianchello','Бьянкелло'),
array('Biancolella','Бьянколелла'),
array('Bical','Бикаль'),
array('Black Muscat','Черный мускат'),
array('Blanc de Morgex','Блан де Моржо'),
array('Blauburger','Блаубургер'),
array('Blauburgunder','Блаубургундер'),
array('Blauer Portugieser','Блауэр Португизер'),
array('Blauer Wildbacher','Блауер Вильдбахер'),
array('Blaufrankisch','Блауфранкиш'),
array('Boal','Боаль'),
array('Bobal','Бобаль'),
array('Bogazkere','Бойязкере'),
array('Bombino Bianco','Бомбино Бьянко'),
array('Bombino Nero','Бомбино Неро'),
array('Bonarda','Бонарда'),
array('Bordeleza Beltza','Бордслеза Бельша'),
array('Bordo','Бордо'),
array('Borracal','Борракал'),
array('Bosco','Боско'),
array('Bouchet','Буше'),
array('Bourboulenc','Бурбуленк'),
array('Bouvier','Бувье'),
array('Bovale Sardo','Бовале Сардо'),
array('Bovaleddu','Боваледду'),
array('Brachetto','Бракетто'),
array('Brancellao','Бранселлао'),
array('Braquet','Браке'),
array('Brown Muscat','Коричневый мускат'),
array('Brunello','Брунелло'),
array('Budeshuri','Будешури'),
array('Bukettraube','Букеттраубе'),
array('Bursona Longanesi','Бурсона Лонганези'),
array('Cabernet Dorsa','Каберне Дорса'),
array('Cabernet Franc','Каберне Фран'),
array('Cabernet Sauvignon','Каберне Совиньон'),
array('Cagnulari','Каньюлари'),
array('Caino Blanco','Каиньо Бланко'),
array('Caino Tinto','Каиньо Тинто'),
array('Calabrese Nero','Калабрезе Неро'),
array('Caladoc','Каладок'),
array('Calitor','Калитор'),
array('Calkarasi','Чал Карасы'),
array('Camarate','Камарате'),
array('Canaiolo','Канайоло'),
array('Cannonau','Каннонау'),
array('Caricalasino','Карикалазино'),
array('Carignan','Кариньян'),
array('Carinena','Кариньена'),
array('Carmenere','Карменер'),
array('Carrasquin','Карраскин'),
array('Carricante','Карриканте'),
array('Casavecchia','Казавеккья'),
array('Casetta','Казетта'),
array('Castelao','Каштелау'),
array('Castelao National','Каштелау Насьональ'),
array('Catalanesca','Каталанеска'),
array('Catarratto','Катарратто'),
array('Catawba','Катавба'),
array('Cayetana','Кайетана'),
array('Cencibel','Сенсибель'),
array('Cerceal','Серсиаль'),
array('Cesanese','Чезанезе'),
array('Cesar','Сезар'),
array('Chambourcin','Шамбурсин'),
array('Chardonnay','Шардоне'),
array('Chasan','Шасан'),
array('Chasselas','Шасла'),
array('Chenin Blanc','Шенен Блан'),
array('Chiavennesca','Кьявеннаска'),
array('Chidiriotiko','Хидириотико'),
array('Chinuri','Чинури'),
array('Chkhaveri','Чхавери'),
array('Cicka','Цицка'),
array('Cienna','Сиенна'),
array('Ciliegiolo','Чильеджоло'),
array('Cimlyanskij Chernyj','Цимлянский черный'),
array('Cinsault','Сенсо'),
array('Citron Cyurupinskiy','Цитрон Цюрупинский'),
array('Citronnyj Magaracha','Цитронный Магарача'),
array('Clairette','Клерет'),
array('Cococciola','Кокочьола'),
array('Coda di Volpe','Кода ди Вольпе'),
array('Codega do Larinho','Кодега до Ларинью'),
array('Colombana','Коломбана'),
array('Colombard','Коломбар'),
array('Colorino','Колорино'),
array('Complexa','Комплекса'),
array('Concord','Конкорд'),
array('Corinto Nero','Коринто Неро'),
array('Cornalin','Корналэн'),
array('Cortese','Кортезе'),
array('Corvina','Корвина'),
array('Corvinone','Корвиноне'),
array('Cot','Кот'),
array('Counoise','Кунуаз'),
array('Criolla Grande','Криолла Гранде'),
array('Croatina','Кроатина'),
array('Crouchen','Крушен'),
array('Cygne Blanc','Чинь Блан'),
array('Delaware','Делавер'),
array('Diagalves','Диагальвес'),
array('Dimiat','Димиат'),
array('Dindarella','Диндарелла'),
array('Diolinoir','Диолинуар'),
array('Dolcetto','Дольчетто'),
array('Dona Blanca','Донья Бланка'),
array('Donzelinho Branco','Донзелиньо Бранко'),
array('Donzelinho Tinto','Донзелиньо Тинто'),
array('Dornfelder','Дорнфельдер'),
array('Drupeggio','Друпеджио'),
array('Dunkelfelder','Дункельфельдер'),
array('Duras','Дюрас'),
array('Durellа','Дурелло'),
array('Durif','Дюриф'),
array('Dutchess','Дачесс'),
array('Dzelshavi','Дзелшави'),
array('Dzhevat Kara','Джеват Кара'),
array('Ehrenfelser','Эренфельсер'),
array('Ekim Kara','Эким-Кара'),
array('Elbling','Эльблинг'),
array('Emerald Riesling','Эмеральд Рислинг'),
array('Emir','Эмир'),
array('Enantio','Энантио'),
array('Encruzado','Энкрузадо'),
array('Erbaluce','Эрбалуче'),
array('Ermitage','Эрмитаж'),
array('Esgana Cao','Эсгана Као'),
array('Espadeiro','Эспадейро'),
array('Esquitxagos','Эскитксагос'),
array('Faber','Фабер'),
array('Falanghina','Фалангина'),
array('Famoso','Фамосо'),
array('Favorito','Фаворито'),
array('Fendant','Фендан'),
array('Fenile','Фениле'),
array('Fer Servadou','Фер Серваду'),
array('Fernao Pires','Фернау Пиреш'),
array('Ferron','Феррон'),
array('Feteasca','Фетяска'),
array('Fiano','Фиано'),
array('Fogoneu','Фогонеу'),
array('Fokiano','Фокиано'),
array('Folgasao','Фольгасао'),
array('Folle Blanche','Фолль Бланш'),
array('Folle Noire','Фолль Нуар'),
array('Forastera','Форастера'),
array('Forcayat','Форкаят'),
array('Fortana','Фортана'),
array('Franconia','Франкония'),
array('Frankovka','Франковка'),
array('Frappato','Фраппато'),
array('Freisa','Фрейза'),
array('Friulano','Фриулано'),
array('Frontignac','Фронтиньяк'),
array('Fruhburgunder','Фрюбургундер'),
array('Fume Blanc','Фюме Блан'),
array('Fumin','Фумэн'),
array('Furmint','Фурминт'),
array('Gaglioppo','Гальоппо'),
array('Gamaret','Гамаре'),
array('Gamay','Гамэ'),
array('Gamba Rossa','Гамба Росса'),
array('Gamza','Гамза'),
array('Garan Dmak','Гаран Дмак'),
array('Garganega','Гарганега'),
array('Garnacha','Гарнача'),
array('Garnacha Blanca','Гарнача Бланка'),
array('Garnacha Gris','Гарнача Грис'),
array('Garnacha Tinta','Гарнача Тинта'),
array('Garnacha Tintorera','Гарнача Тинторера'),
array('Garro','Гарро'),
array('Gars Levelyu','Гарс Левелю'),
array('Gekber Muskateller','Гелбер Мускателлер'),
array('Gewurztraminer','Гевюрцтраминер'),
array('Glera','Глера'),
array('Godello','Годельо'),
array('Goldmuskateller','Голдмускателлер'),
array('Golubok','Голубок'),
array('Gordo Blanco','Гордо Банко'),
array('Goruli Mcvane','Горули Мцване'),
array('Gouais Blanc','Гуйяс Блан'),
array('Goustolidi','Густолиди'),
array('Gouveio','Гувейо'),
array('Graciano','Грасиано'),
array('Grand Noir','Гран Нуар'),
array('Grande Vidure','Гранде Видуре'),
array('Grappello Ruberti','Граппелло Руберти'),
array('Grasa','Граса'),
array('Grasevina','Грашевина'),
array('Grauburgunder','Граубургундер'),
array('Grecanico Dorato','Греканико Дорато'),
array('Grechetto','Гречетто'),
array('Greco Bianco','Греко Бьянко'),
array('Greco Nero','Греко Неро'),
array('Grenache Blanc','Гренаш Блан'),
array('Grenache Gris','Гренаш Гри'),
array('Grenache Noir','Гренаш Нуар'),
array('Grignolino','Гриньолино'),
array('Grillo','Грилло'),
array('Grolleau','Гролло'),
array('Groppello','Гропелло'),
array('Gros Manseng','Гро Мансан'),
array('Gruner Veltliner','Грюнер Вельтлинер'),
array('Gutedel','Гутедель'),
array('Gyulyabi','Гюляби'),
array('Haghtanak','Ахтанак'),
array('Hanepoot','Хейнпут'),
array('Harriague','Харригуа'),
array('Harslevelu','Харшлевелю'),
array('Hatmi','Хатми'),
array('Hatun Hardzhi','Хатун Харджи'),
array('Heida','Хайда'),
array('Hondarrabi Beltza','Ондарраби Бельтца'),
array('Hondarrabi Zerratia','Ондарраби Серратия'),
array('Hondarrabi Zuri','Ондарраби Сури'),
array('Humagne Blanche','Уман Бланш'),
array('Humagne Rouge','Уман Руж'),
array('Huxelrebe','Хуксельребе'),
array('Incrocio Manzoni','Инкрочио Манзони'),
array('Inzolia','Инзолия'),
array('Irsay Oliver','Иршаи Оливер'),
array('Isabella','Изабелла'),
array('Itasca','Айтаска'),
array('Jacquere','Жакер'),
array('Jaen','Жаен'),
array('Joao de Santarem','Жоау де Сантарем'),
array('Juan Garcia','Хуан Гарсия'),
array('Jurancon Noir','Жюрансон Нуар'),
array('Kachichi','Качичи'),
array('Kadarka','Кадарка'),
array('Kahet','Кахет'),
array('Kakotrygis','Какотригис'),
array('Kalecik Karasi','Каледжик Карасы'),
array('Kangun','Кангун'),
array('Karasakiz','Карасакыз'),
array('Katalon Zimnij','Каталон Зимний'),
array('Kefesiya','Кефесия'),
array('Kekfrankos','Кекфранкош'),
array('Keknyelu','Кекнелю'),
array('Kekoporto','Кекопорто'),
array('Kerner','Кернер'),
array('Khihvi','Хихви'),
array('Khndokhni','Хндохни'),
array('Kidonitsa','Кидоница'),
array('Kisi','Киси'),
array('Kokur','Кокур'),
array('Koniaros','Кониарос'),
array('Kotsifali','Коцифали'),
array('Krahuna','Крахуна'),
array('Krasnostop','Красностоп'),
array('Krassato','Красато'),
array('Lacrima','Лакрима'),
array('Lagorthi','Лагорти'),
array('Lagrein','Лагрейн'),
array('Lambrusco','Ламбруско'),
array('Lambrusco di Sorbara','Ламбруско ди Сорбара'),
array('Lambrusco Grasparossa','Ламбруско Граспаросса'),
array('Lambrusco Salamino','Ламбруско Саламино'),
array('Laski Rizling','Ласки Ризлинг'),
array('Leanka','Леанка'),
array('Lemberger','Лимбергер'),
array('Len de L\'el','Лен де Л\'эль'),
array('Liatiko','Лиатико'),
array('Lidiya','Лидия'),
array('Limnio','Лимнио'),
array('Limniona','Лимниона'),
array('Listan','Листан'),
array('Listan Negro','Листан Негро'),
array('Lladoner Pelut','Льядонер Пелю'),
array('Loureiro','Лоурейро'),
array('Lumassina','Лумассина'),
array('Macabeo','Макабео'),
array('Madeleine Angevine','Мадлен Анжевин'),
array('Magliocco Canino','Мальокко Канино'),
array('Magliocco Dolce','Мальокко Дольче'),
array('Maidiran','Мадиран'),
array('Malagousia','Малагузия'),
array('Malbec','Мальбек'),
array('Malbo Gentile','Мальбо Джентиле'),
array('Malvar','Мальвар'),
array('Malvasia','Мальвазия'),
array('Malvasia Bianca','Мальвазия Бьянка'),
array('Malvasia del Lazio','Мальвазия дель Лацио'),
array('Malvasia di Candia','Мальвазия ди Кандия'),
array('Malvasia Fina','Мальвазия Фина'),
array('Malvasia Istriana','Мальвазия Истриана'),
array('Malvasia Nera','Мальвазия Нера'),
array('Malvasia Nera di Brindisi','Мальвазия Нера ди Бриндизи'),
array('Malvasia Nera di Lecce','Мальвазия Нера ди Лече'),
array('Malvasia Rosada','Мальвазия Росада'),
array('Mammolo','Маммоло'),
array('Mandilaria','Мандилария'),
array('Mando','Мандо'),
array('Manto Negro','Манто Негро'),
array('Mantonegre-Fogoneu','Мантонегре-Фогоню'),
array('Mantonico','Мантонико'),
array('Manzoni Bianco','Манзони Бьянко'),
array('Marechal Foch','Маршаль Фош'),
array('Maria Gomes','Мария Гомес'),
array('Marquette','Маркетт'),
array('Marsanne','Марсан'),
array('Marselan','Марселан'),
array('Marzemino','Марцемино'),
array('Mataossu','Матаоссу'),
array('Mataro','Матаро'),
array('Matrasa','Матраса'),
array('Maturana','Матурана'),
array('Mauzac','Мозак'),
array('Mavro','Мавро'),
array('Mavro Kalavritino','Мавро Калавритино'),
array('Mavro Messenikola','Мавро Месеникола'),
array('Mavrodaphne','Мавродафне'),
array('Mavrotragano','Мавротрагано'),
array('Mavroudi','Мавроуди'),
array('Mavrud','Мавруд'),
array('Mayolet','Майоле'),
array('Mazuelo','Масуэло'),
array('Mcvane','Мцване'),
array('Melnik','Мелник'),
array('Melon de Bourgogne','Мелонь де Бургонь'),
array('Mencia','Менсия'),
array('Merenzao','Меренсао'),
array('Merlot','Мерло'),
array('Merseguera','Мерсегера'),
array('Mervakh','Мервах'),
array('Minella Bianco','Минелла Бьянко'),
array('Minella Nera','Минелла Нера'),
array('Misket','Мискет'),
array('Mission','Мишн'),
array('Molette','Молетт'),
array('Molinara','Молинара'),
array('Monastrell','Монастрель'),
array('Mondeuse Noire','Мондес Нуар'),
array('Monemvasia','Монемвасия'),
array('Monica','Моника'),
array('Montepulciano','Монтепульчано'),
array('Morellino','Мореллино'),
array('Morillon','Мориллон'),
array('Morio Muskat','Морио Мускат'),
array('Moristel','Мористель'),
array('Moscatel','Москатель'),
array('Moscatel de Gran Menudo','Москатель де Грано Менудо'),
array('Moscatel de Setubal','Москатель де Сетубал'),
array('Moscatel Galego','Москатель Гальего'),
array('Moscatel Roxo','Мушкатель Рошу'),
array('Moscato Bianco','Москато Бьянко'),
array('Moscato di Alexandria','Москатель де Александрия'),
array('Moscato Giallo','Москато Джалло'),
array('Moscato Rosa','Москато Роза'),
array('Moschofilero','Мосхофилеро'),
array('Mouraton','Моуратон'),
array('Mourisco','Муриско'),
array('Mourvedre','Мурведр'),
array('Moustrou','Мостроу'),
array('Mshali','Мсхали'),
array('Mudjuretuli','Муджуретули'),
array('Mullerebe','Мюллерребе'),
array('Muller-Thurgau','Мюллер-Тургау'),
array('Muscadelle','Мюскадель'),
array('Muscadet','Мюскаде'),
array('Muscardin','Мюскардин'),
array('Muscat','Мускат'),
array('Muscat Amber','Мускат Янтарный'),
array('Muscat Blanc a Petits Grains','Мускат Блан а Пти Гран'),
array('Muscat Canelli','Мускат Канелли'),
array('Muscat d’Alsace','Мускат Эльзасский'),
array('Muscat de Frontignan','Мускат де Фронтиньян'),
array('Muscat Lunel','Мускат Люнель'),
array('Muscat of Alexandria','Мускат Александрийский'),
array('Muscat of Hamburg','Мускат Гамбургский'),
array('Muscat Ottonel','Мускат Оттонель'),
array('Muscat Rose','Мускат Розовый'),
array('Muskateller','Мускателлер'),
array('Muskat-Silvaner','Мускат-Сильванер'),
array('Muskotaly','Мушкотай'),
array('Narince','Нариндже'),
array('Narma','Нарма'),
array('Nascetta','Нашетта'),
array('Nasco','Наско'),
array('Nebbiolo','Неббиоло'),
array('Negoska','Негоска'),
array('Negramoll','Неграмоль'),
array('Negrara','Неграра'),
array('Negrette','Негрет'),
array('Negroamaro','Негроамаро'),
array('Negru de Dragasani','Негру де Драгашани'),
array('Nerello Cappuccio','Нерелло Каппуччио'),
array('Nerello Mascalese','Нерелло Маскалезе'),
array('Nero Buono','Неро Буоно'),
array('Nero d\'Avola','Неро д\'Авола'),
array('Nero di Troia','Неро ди Троя'),
array('Neuburger','Нойбургер'),
array('Niagara','Ниагара'),
array('Nieddera','Ниеддера'),
array('Nielluccio','Ниеллучио'),
array('Nocera','Ночера'),
array('Nosiola','Нозиола'),
array('Nouvelle','Нувель'),
array('Novelle','Новелле'),
array('Nuragus','Нурагус'),
array('Obaide','Обайде'),
array('Odessa Black','Одесский Черный'),
array('Ojaleshi','Оджалеши'),
array('Okuzgozu','Окюзгезю'),
array('Olasz Rizling','Олас Ризлинг'),
array('Ondenc','Онден'),
array('Oporto','Опорто'),
array('Optima','Оптима'),
array('Orange Muscat','Оранжевый Мускат'),
array('Ormeasco','Ормеаско'),
array('Ortega','Ортега'),
array('Ortrugo','Ортруго'),
array('Oseleta','Озелета'),
array('Otskhanuri Sapere','Оцханури Сапере'),
array('Pagadebit','Пагадебит'),
array('Pais','Паис'),
array('Palava','Палава'),
array('Pallagrello Bianco','Паллагрелло Бьянко'),
array('Pallagrello Nero','Паллагрелло Неро'),
array('Palomino Fino','Паломино'),
array('Pamidi','Памид'),
array('Pampanuto','Пампануто'),
array('Pansa Blanca','Панса Бланка'),
array('Papaskarasi','Папаска Черна'),
array('Pardillo','Пардилло'),
array('Parellada','Парельяда'),
array('Parreleta','Паррелета'),
array('Passerina','Пассерина'),
array('Pecorello','Пекорелло'),
array('Pecorino','Пекорино'),
array('Pederna','Педерна'),
array('Pedro Ximenez','Педро Хименес'),
array('Pelaverga','Пелаверга'),
array('Periquita','Перикита'),
array('Perlan','Перлан'),
array('Perricone','Перриконе'),
array('Persan','Персан'),
array('Petit Arvine','Пти Арвин'),
array('Petit Courbu','Пти Курбю'),
array('Petit Manseng','Пти Мансан'),
array('Petit Rouge','Пти Руж'),
array('Petit Sirah','Петит Сира'),
array('Petit Verdot','Пти Вердо'),
array('Phoenix','Феникс'),
array('Picapoll Blanca','Пикаполь Бланка'),
array('Picolit','Пиколит'),
array('Piedirosso','Пьедироссо'),
array('Pigato','Пигато'),
array('Pignoletto','Пиньолетто'),
array('Pignolo','Пиньоло'),
array('Pineau d\'Aunis','Пино д\'Онис'),
array('Pinot Beurot','Пино Боро'),
array('Pinot Bianco','Пино Бьянко'),
array('Pinot Blanc','Пино Блан'),
array('Pinot Grigio','Пино Гриджио'),
array('Pinot Gris','Пино Гри'),
array('Pinot Meunier','Пино Менье'),
array('Pinot Nero','Пино Неро'),
array('Pinot Noir','Пино Нуар'),
array('Pinotage','Пинотаж'),
array('Piquepoul','Пикпуль'),
array('Planta Nova','Планта Нова'),
array('Plavac Mali','Плавац Мали'),
array('Portugieser','Португизер'),
array('Poulsard','Полсар'),
array('Pressac','Прессак'),
array('Preto Martinho','Прету Мартиньо'),
array('Prieto Picudo','Прието Пикудо'),
array('Primitivo','Примитиво'),
array('Procanico','Проканико'),
array('Prokupac','Прокупац'),
array('Prugnolo Gentile','Пруньоло Джентиле'),
array('Pugnitello','Пунителло'),
array('Rabigato','Рабигато'),
array('Rabo de Ovelha','Рабо де Овелья'),
array('Raboso','Рабозо'),
array('Ramisco','Рамиско'),
array('Rara Neagra','Рара Нягрэ'),
array('Rebo','Ребо'),
array('Refosco','Рефоско'),
array('Regent','Регент'),
array('Reichensteiner','Райхенштайнер'),
array('Rheinriesling','Рейнрислинг'),
array('Ribolla Gialla','Риболла Джалла'),
array('Rieslaner','Рисланер'),
array('Riesling','Рислинг'),
array('Rivaner','Риванер'),
array('Rkatsiteli','Ркацители'),
array('Robola','Робола'),
array('Roditis','Родитис'),
array('Rolle','Ролле'),
array('Romorantin','Роморантен'),
array('Rondinella','Рондинелла'),
array('Roscetto','Рошетто'),
array('Rossese','Россезе'),
array('Rossignolla','Россиньола'),
array('Rossola Nera','Россола Нера'),
array('Roter Veltliner','Ротер Вельтлинер'),
array('Rotgipfler','Ротгипфлер'),
array('Roupeiro','Роупейру'),
array('Roussanne','Руссан'),
array('Roussette','Руссет'),
array('Rubin','Рубин'),
array('Ruby Cabernet','Руби Каберне'),
array('Ruche','Руке'),
array('Rufete','Руфет'),
array('Rulander','Руландер'),
array('Sacy','Саси'),
array('Sagrantino','Сагрантино'),
array('Saint Laurent','Сен Лоран'),
array('Samling 88','Самлинг 88'),
array('Samso','Самсо'),
array('San Lorenzo','Сан Лоренцо'),
array('Sangiovese','Санджовезе'),
array('Saperavi','Саперави'),
array('Sary Pandas','Сары Пандас'),
array('Sauvignon Blanc','Совиньон Блан'),
array('Sauvignon Green','Совиньон Зелёный'),
array('Sauvignon Gris','Совиньон Гри'),
array('Sauvignon Tasca','Совиньон Таска'),
array('Savagnin','Саваньен'),
array('Savatiano','Саватьяно'),
array('Scheurebe','Шойребе'),
array('Schiava','Скьява'),
array('Schonburger','Шонбургер'),
array('Schwarzriesling','Шварцрислинг'),
array('Sciacarello','Шьякарелло'),
array('Sciascinoso','Щащинозо'),
array('Scioppettino','Скьоппеттино'),
array('Scuppernong','Скаппернонг'),
array('Seara Nova','Сеара Нова'),
array('Seibel','Зайбель'),
array('Semillon','Семильон'),
array('Serin','Серин'),
array('Seyval Blanc','Сейваль Блан'),
array('Sgavetta','Сгаветта'),
array('Shavkapito','Шавкапито'),
array('Shereini Bela','Шерейни Бела'),
array('Shiraz','Шираз'),
array('Sibirkovyj','Сибирьковый'),
array('Sideritis','Сидеритис'),
array('Siegerrebe','Зигерребе'),
array('Silvaner','Сильванер'),
array('Siria','Сириа'),
array('Solaris','Солярис'),
array('Solnechnodolinskiy','Солнечнодолинский'),
array('Sousao','Сузао'),
array('Souson','Соусон'),
array('Spanna','Спанна'),
array('Spatburgunder','Шпетбургундер'),
array('Sultaniye','Султани'),
array('Sumoll','Сумолл'),
array('Susumaniello','Сузуманьелло'),
array('Syrah','Сира'),
array('Tai Rosso','Тай Россо'),
array('Tamarez','Тамарес'),
array('Tannat','Таннат'),
array('Tarrango','Тарранго'),
array('Tavkveri','Тавквери'),
array('Tazzelenghe','Таццеленге'),
array('Telti Kuruk','Тельти Курук'),
array('Tempranillo','Темпранильо'),
array('Tempranillo Blanco','Темпранильо Бланко'),
array('Teroldego','Терольдего'),
array('Terrano','Террано'),
array('Terrantez','Террантез'),
array('Terret Blanc','Террет Блан'),
array('Terret Bourret','Террет Буре'),
array('Terret Noir','Террет Нуар'),
array('Tetra','Тетра'),
array('Tibourene','Тибурен'),
array('Timorasso','Тиморассо'),
array('Tinta Amarela','Тинта Амарела'),
array('Tinta Barroca','Тинта Баррока'),
array('Tinta Caiada','Тинта Кайада'),
array('Tinta de Barka','Тинта да Барка'),
array('Tinta de Toro','Тинта де Торо'),
array('Tinta del Pais','Тинто дель Паис'),
array('Tinta Francisca','Тинта Франциска'),
array('Tinta Miuda','Тинта Миуда'),
array('Tinta Negra Mole','Тинта Негра Моле'),
array('Tinta Roriz','Тинта Рориш'),
array('Tintilla','Тинтилья'),
array('Tintilla de Rota','Тинтилья де Рота'),
array('Tinto Cao','Тинто Као'),
array('Tinto Fino','Тинто Фино'),
array('Tinto Velasco','Тинто Веласко'),
array('Tokay','Токай'),
array('Torrontes','Торронтес'),
array('Tourbat','Торбато'),
array('Touriga Franca','Турига Франка'),
array('Touriga Nacional','Турига Насьональ'),
array('Tozot','Тозот'),
array('Traminer','Траминер'),
array('Trebbianello','Треббьянелло'),
array('Trebbiano','Треббьяно'),
array('Trebbiano d\'Abruzzo','Треббьяно д\'Абруццо'),
array('Trebbiano di Lugana','Треббьяно ди Лугана'),
array('Trebbiano di Soave','Треббьяно ди Соаве'),
array('Trebbiano Giallo','Треббьяно Джалло'),
array('Trebbiano Romagnolo','Треббьяно Романьоло'),
array('Trebbiano Toscano','Треббьяно Тоскано'),
array('Treixadura','Трейскадура'),
array('Trepat','Трепат'),
array('Tressallier','Тресалье'),
array('Trincadeira','Тринкадейра'),
array('Trollinger','Троллингер'),
array('Trousseau','Труссо'),
array('Tsolikouri','Цоликоури'),
array('Turbiana','Турбиана'),
array('Ugni Blanc','Уни Блан'),
array('Ull de Llebre','Уль де Льебре'),
array('Usakhelauri','Усахелаури'),
array('Uva di Troia','Ува ди Троя'),
array('Uva Rara','Ува Рара'),
array('Uva Rilla','Ува Рилла'),
array('Vaccarese','Ваккарез'),
array('Valdiguie','Вальдигуэ'),
array('Veltliner','Вельтлинер'),
array('Veltliner Rosato','Вельтлинер Розато'),
array('Verdeca','Вердека'),
array('Verdejo','Вердехо'),
array('Verdello','Вердельо'),
array('Verdicchio','Вердиккио'),
array('Verdil','Вердил'),
array('Verdiso','Вердисо'),
array('Verdoncho','Вердончо'),
array('Verduzzo','Вердуццо'),
array('Vermentino','Верментино'),
array('Vermentino Nero','Верментино Неро'),
array('Vernaccia','Верначча'),
array('Vernatsch','Вернач'),
array('Vespaiolo','Веспайола'),
array('Vespolina','Весполина'),
array('Vidal','Видал'),
array('Vidiano','Видиано'),
array('Vijariego Negro','Вихарьего Негро'),
array('Vilana','Вилана'),
array('Vinhao','Виньяу'),
array('Viognier','Вионье'),
array('Viorika','Виорика'),
array('Viosinho','Виозиньо'),
array('Vital','Витал'),
array('Vitovska','Витовска'),
array('Viura','Виура'),
array('Voskeat','Воскеат'),
array('Vranaz','Вранац'),
array('Wanderbara','Вандербара'),
array('Weissburgunder','Вайсбургундер'),
array('Welschriesling','Вельшрислинг'),
array('Xarel-lo','Ксарельо'),
array('Xinomavro','Ксиномавро'),
array('Xynisteri','Ксинистери'),
array('Zalema','Залема'),
array('Zeta','Зета'),
array('Zibibbo','Зибиббо'),
array('Zierfandler','Цирфандлер'),
array('Zilavka','Жилавка'),
array('Zinfandel','Зинфандель'),
array('Zweigelt','Цвайгельт')
);