<?php
$appellation_list = array(
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Colli Aprutini','Колли Апрутини'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Colline Pescaresi','Коллине Пескарези'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Colline Teatine','Коллине Театине'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Controguerra','Контрогуэрра'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Montepulciano d\'Abruzzo','Монтепульчано д\'Абруццо'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Montepulciano d\'Abruzzo Colline Teramane','Монтепульчано д\'Абруццо Коллине Терамане'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Terre di Chieti','Терре ди Кьети'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Terre Tollesi','Терре Толлези'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Trebbiano d\'Abruzzo','Треббьяно д\'Абруццо'),
array('Italy','Италия','Abruzzo','Абруццо','Abruzzo','Абруццо','Cerasuolo d\'Abruzzo','Черазуоло д\'Абруццо'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Albana di Romagna','Альбана Ди Романья'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Bosco Eliceo','Боско Эличео'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Colli Bolognesi','Колли Болоньези'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Colli Piacentini','Колли Пьячентини'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Colli d\'Imola','Колли д\'Имола'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Colli della Romagna Centrale','Колли делла Романья Централе'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Colli di Faenza','Колли ди Фаэнца'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Colli di Parma','Колли ди Парма'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Colli di Rimini','Колли ди Римини'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Colli di Scandiano e di Canossa','Колли ди Скандиано э ди Каносса'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Emilia','Эмилия'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Lambrusco Grasparossa di Castelvetro','Ламбруско Граспаросса ди Кастельветро'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Lambrusco Salamino di Santa Croce','Ламбруско Саламино ди Санта Кроче'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Lambrusco di Sorbara','Ламбруско ди Сорбара'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Modena','Модена'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Reggiano','Реджано'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Reno','Рено'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Romagna','Романья'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Rubicone','Рубикон'),
array('Italy','Италия','Emilia-Romagna','Эмилия-Романья','Emilia-Romagna','Эмилия-Романья','Trebbiano di Romagna','Треббьяно ди Романья'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Aleatico di Gradoli','Алеатико ди Градоли'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Aprilia','Априлия'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Atina','Атина'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Bianco Capena','Бьянко Капена'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Castelli Romani','Кастелли Романи'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Cerveteri','Черветери'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Cesanese del Piglio','Чезанезе дель Пильо'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Cesanese di Affile','Чезанезе ди Аффиле'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Cesanese di Olevano Romano','Чезанезе ди Олевано Романо'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Circeo','Чирчео'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Civitella d\'Agliano','Чивителла д\'Альяно'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Colli Albani','Колли Альбани'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Colli Etruschi Viterbesi','Колли Этруски Витербези'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Colli Lanuvini','Колли Ланувини'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Colli della Sabina','Колли делла Сабина'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Cori','Кори'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Est! Est!! Est!!! di Montefiascone','Эст! Эст!! Эст!!! Ди Монтефиасконе'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Frascati','Фраскати'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Frusinate','Фрузинате'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Genazzano','Дженаццано'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Lazio','Лацио'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Marino','Марино'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Montecompatri Colonna','Монтекомпатри Колонна'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Nettuno','Неттуно'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Roma','Рома'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Tarquinia','Тарквиния'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Velletri','Веллетри'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Vignanello','Виньянелло'),
array('Italy','Италия','Lazio','Лацио','Lazio','Лацио','Zagarolo','Дзагароло'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Bianchello di Metauro','Бьянкелло дель Метауро'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Colli Maceratesi','Колли Мачератези'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Colli Pesaresi','Колли Пезарези'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Conero','Конеро'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Esino','Эзино'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Falerio','Фалерио'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Lacrima di Morro d\'Alba','Лакрима ди Морро д\'Альба'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Marche','Марке'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Offida','Оффида'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Pergola','Пергола'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Rosso Conero','Россо Конеро'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Rosso Piceno','Россо Пичено'),
array('Italy','Италия','Marche','Марке','Marche','Марке','San Ginesio','Сан Джинезио'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Serrapetrona','Серрапетрона'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Terreni di Sanseverino','Террени ди Сансеверино'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Verdicchio dei Castelli di Jesi','Вердиккио дей Кастелли ди Йези'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Verdicchio di Matelica','Вердиккио ди Мателика'),
array('Italy','Италия','Marche','Марке','Marche','Марке','Vernaccia di Serrapetrona','Верначча ди Серрапетрона'),
array('Italy','Италия','Molise','Молизе','Molise','Молизе','Biferno','Биферно'),
array('Italy','Италия','Molise','Молизе','Molise','Молизе','Molise','Молизе'),
array('Italy','Италия','Molise','Молизе','Molise','Молизе','Pentro di Isernia','Пентро д\'Изерния'),
array('Italy','Италия','Molise','Молизе','Molise','Молизе','Terre degli Osci','Терре дельи Оши'),
array('Italy','Италия','Molise','Молизе','Molise','Молизе','Tintilia del Molis','Тинтилия дель Молизе'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Bianco dell\'Empolese','Бьянко делл’Эмполезе'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Barco Reale di Carmignano','Барко Реале Ди Карминьяно'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Bianco di Pitigliano','Бьянко ди Питильяно'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Bolgheri','Болгери'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Bolgheri Sassicaia','Bolgheri Sassicaia'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Brunello di Montalcino','Брунелло ди Монтальчино'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Candia dei Colli Apuani','Кандия деи Колли Апуани'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Capalbio','Капальбио'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Carmignano','Карминьяно'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Chianti','Кьянти'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Chianti Classico','Кьянти Классико'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Colli dell\'Etruria Centrale','Колли делл’Этрурия Чентрале'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Colline Lucchesi','Коллине Луккези'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Cortona','Кортона'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Ansonica Costa dell\'Argentario','Ансоника Коста дель\'Арджентарио'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Elba','Эльба'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Elba Aleatico Passito','Эльба Алеатико Пассито'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Grance Senesi','Гранче Сенези'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Maremma Toscana','Маремма Тоскана'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Montecarlo','Монтекарло'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Montecucco','Монтекукко'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Montecucco Sangiovese','Монтекукко Санджовезе'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Monteregio di Massa Marittima','Монтереджо ди Масса Мариттима'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Montescudaio','Монтескудайо'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Morellino di Scansano','Мореллино ди Сканзано'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Moscadello di Montalcino','Москаделло ди Монтальчино'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Orcia','Орча'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Parrina','Паррина'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Pomino','Помино'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Rosso di Montalcino','Россо ди Монтальчино'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Rosso di Montepulciano','Россо ди Монтепульчано'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Vernaccia di San Gimignano','Верначча ди Сан Джиминьяно'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','San Gimignano','Сан Джиминьяно'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','San Torpe','Сан Торпе'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Sant\'Antimo','Сант\'Антимо'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Sovana','Сована'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Suvereto','Суверето'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Terratico di Bibbona','Терратико ди Бибона'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Terre di Casole','Терре ди Казоле'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Toscana','Тоскана'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Terre di Pisa','Терре ди Пиза'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Val d\'Arbia','Валь д\'Арбия'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Val di Cornia','Валь ди Корния'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Valdarno di Sopra','Вальдарно ди Сопра'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Valdichiana','Вальдикьяна'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Valdinievole','Валдиниеволе'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Vin Santo','Вин Санто'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Vino Nobile di Montepulciano','Вино Нобиле ди Монтепульчано'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Vin Santo del Chianti','Вин Санто дель Кьянти'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Vin Santo di Carmignano','Вин Санто Ди Карминьяно'),
array('Italy','Италия','Toscana','Тоскана','Toscana','Тоскана','Vin Santo di Montepulciano','Вин Санто ди Монтепульчано'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Assisi','Ассизи'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Amelia','Амелия'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Colli Altotiberini','Колли Альтотиберини'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Colli Martani','Колли Мартани'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Colli Perugini','Колли Перуджини'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Colli del Trasimeno','Колли дель Тразимено'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Lago di Corbara','Лаго ди Корбара'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Montefalco','Монтефалько'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Montefalco Sagrantino','Монтефалько Сагрантино'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Rosso Orvietano','Россо Орвието'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Orvieto','Орвието'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Spoleto','Сполето'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Todi','Тоди'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Torgiano','Торджано'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Torgiano Rosso Riserva','Торджано Россо Ризерва'),
array('Italy','Италия','Umbria','Умбрия','Umbria','Умбрия','Umbria','Умбрия'),
array('Italy','Италия','Valle d\'Aosta','Валле д\'Аоста','Valle d\'Aosta','Валле д\'Аоста','Arnad-Montjovet','Арнад-Монжове'),
array('Italy','Италия','Valle d\'Aosta','Валле д\'Аоста','Valle d\'Aosta','Валле д\'Аоста','Chambave','Шамбав'),
array('Italy','Италия','Valle d\'Aosta','Валле д\'Аоста','Valle d\'Aosta','Валле д\'Аоста','Donnas','Доннас'),
array('Italy','Италия','Valle d\'Aosta','Валле д\'Аоста','Valle d\'Aosta','Валле д\'Аоста','Enfer d\'Arvier','Энфе д\'Арвье'),
array('Italy','Италия','Valle d\'Aosta','Валле д\'Аоста','Valle d\'Aosta','Валле д\'Аоста','Morgex et de la Salle','Морже и Ла Саль'),
array('Italy','Италия','Valle d\'Aosta','Валле д\'Аоста','Valle d\'Aosta','Валле д\'Аоста','Nus','Нюс'),
array('Italy','Италия','Valle d\'Aosta','Валле д\'Аоста','Valle d\'Aosta','Валле д\'Аоста','Torrette','Торретте'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Cinque Terre','Чинкве Терре'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Colli di Luni','Колли ди Луни'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Colline Savonesi','Коллине Савонези'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Colline del Genovesato','Коллине дель Дженовесато'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Colline di Levanto','Коллине ди Леванто'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Golfo del Tigullio-Portofino','Гольфо дель Тигуллио-Портофино'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Pornassio','Порнассио'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Riviera Ligure di Ponente','Ривьера Лигуре ди Поненте'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Rossese di Dolceacqua','Россезе ди Дольчеаква'),
array('Italy','Италия','Liguria','Лигурия','Liguria','Лигурия','Val Polcevera','Валь Польчевера'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Alto Mincio','Альто Минчо'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Benaco Bresciano','Бенако Брешиано'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Bergamasca','Бергамаска'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Botticino','Боттичино'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Capriano del Colle','Каприано дель Колле'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Casteggio','Кастеджо'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Cellatica','Челлатика'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Curtefranca','Куртефранка'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Franciacorta','Франчакорта'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Garda Colli Mantovani','Гарда Колли Мантовани'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Garda','Гарда'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Lambrusco Mantovano','Ламбруско Мантовано'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Lugana','Лугана'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Provincia di Mantova','Провинция Мантуя'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Provincia di Pavia','Провинция Павиа'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Moscato di Scanzo','Москато ди Сканцо'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Oltrepo Pavese','Ольтрепо Павезе'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Quistello','Куистелло'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Riviera del Garda Bresciano','Ривьера дель Гарда Брешиано'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Sabbioneta','Саббьонета'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','San Colombano al Lambro','Сан Коломбано аль Ламбро'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','San Martino della Battaglia','Сан Мартино делла Батталья'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Sebino','Себино'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Terrazze Retiche di Sondrio','Террацце Ретике ди Сондрио'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Terre del Colleoni','Терре дель Коллеоне'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Valcalepio','Валькалепио'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Valtellina','Вальтеллина'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Rosso di Valtellina','Россо ди Вальтеллина'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Sforzato di Valtellina','Сфурсат ди Вальтеллина'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Valtellina Superiore','Вальтеллина Супериоре'),
array('Italy','Италия','Lombardy','Ломбардия','Lombardy','Ломбардия','Valtenesi','Вальтенези'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Alba','Альба'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Albugnano','Альбуньяно'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Alta Langa','Альта Ланга'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Asti','Асти'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Barbaresco','Барбареско'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Barbera d\'Alba','Барбера д\'Альба'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Barbera d\'Asti','Барбера д\'Асти'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Barbera del Monferrato','Барбера дель Монферрато'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Barolo','Бароло'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Boca','Бока'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Brachetto d\'Acqui','Бракетто д\'Акуи'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Bramaterra','Браматерра'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Calosso','Калоссо'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Canavese','Канавезе'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Carema','Карема'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Cisterna d\'Asti','Чистерна д\'Асти'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Colli Tortonesi','Колли Тортонези'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Collina Torinese','Коллина Торинезе'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Colline Novaresi','Коллине Новарези'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Colline Saluzzesi','Коллине Салуццези'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Cortese dell\'Alto Monferrato','Кортезе делль Альто Монферрато'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Coste della Sesia','Косте делла Сесия'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Dogliani','Дольяни'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Dolcetto d\'Acqui','Дольчетто д\'Акви'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Dolcetto d\'Alba','Дольчетто д\'Альба'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Dolcetto d\'Asti','Дольчетто д\'Асти'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Dolcetto di Diano d\'Alba','Дольчетто ди Диано д\'Альба'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Dolcetto di Ovada','Дольчетто ди Овада'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Erbaluce di Caluso','Эрбалуче ди Калузо'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Fara','Фара'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Freisa d\'Asti','Фреиза д’Асти'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Freisa di Chieri','Фреиза ди Кьери'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Gabiano','Габьяно'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Gattinara','Гаттинара'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Gavi','Гави'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Ghemme','Гемме'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Grignolino d\'Asti','Гриньолино д\'Асти'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Grignolino del Monferrato Casalese','Гриньолино дель Монферрато Казалезе'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Langhe','Ланге'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Lessona','Лессона'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Loazzolo','Лоаццоло'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Malvasia di Casorzo d\'Asti','Мальвазия ди Казорцо д\'Асти'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Malvasia di Castelnuovo Don Bosco','Мальвазия ди Кастельнуово Дон Боско'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Monferrato','Монферрато'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Moscato d\'Asti','Москато д\'Асти'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Nebbiolo d\'Alba','Неббило д\'Альба'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Piemonte','Пьемонт'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Pinerolese','Пинеролезе'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Roero','Роеро'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Rubino di Cantavenna','Рубино ди Кантавенна'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Ruche di Castagnole Monferrato','Руке ди Кастаньоле Монферрато'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Sizzano','Сиццано'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Strevi','Стреви'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Terre Alfieri','Терре Алфьери'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Valli Ossolane','Валли Оссолане'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Valsusa','Валсуза'),
array('Italy','Италия','Piemonte','Пьемонт','Piemonte','Пьемонт','Verduno Pelaverga','Вердуно Пелаверга'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Carso','Карсо'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Colli Orientali del Friuli','Колли Орьентали Фриули'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Collio','Коллио'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Delle Venezie','Делле Венеция'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli Annia','Фриули Анниа'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli Aquileia','Фриули Аквилея'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli Grave','Фриули Грав'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli Isonzo','Фриули Изонцо'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli Latisana','Фриули Латизана'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Lison Pramaggiore','Лизон Прамаджоре'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Ramandolo','Рамандоло'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Rosazzo','Розаццо'),
array('Italy','Италия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Friuli-Venezia Giulia','Фриули-Венеция Джулия','Venezia Giulia','Венеция-Джулия'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Sudtirol Alto Adige','Судтироль Альто-Адидже'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Casteller','Кастеллер'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Lago di Caldaro','Лаго ди Кальдаро'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Teroldego Rotaliano','Терольдего Роталиано'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino','Трентино'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Trento','Тренто'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Valdadige','Вальдадидже'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Valdadige Terradeiforti','Вальдадидже Террадеифорти'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Vallagarina','Валлагарина'),
array('Italy','Италия','Trentino-Alto Adige','Трентино-Альто-Адидже','Trentino-Alto Adige','Трентино-Альто-Адидже','Vigneti delle Dolomiti','Виньети делле Доломити'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Amarone della Valpolicella','Амароне делла Вальполичелла'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Arcole','Арколе'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Bagnoli Friularo','Баньоли Фриуларо'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Bagnoli di Sopra','Баньоли ди Сопра'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Bardolino','Бардолино'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Bardolino Superiore','Бардолино Супериоре'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Bianco di Custoza','Бьянко ди Кустоза'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Breganze','Бреганце'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Delle Venezie','Делле Венеция'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Colli Berici','Колли Беричи'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Colli Euganei','Колли Эвганеи'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Colli Euganei Fior d\'Arancio','Колли Эвганеи Фьор д’Аранчо'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Colli di Conegliano','Колли ди Конельяно'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Corti Benedettine del Padovano','Корти Бенедеттине дель Падовано'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Gambellara','Гамбеллара'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Garda Veneto','Гарда Венето'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Lessini Durello','Лессини Дурелло'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Monti Lessini','Монти Лессини'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Lison','Лизон'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Lison Pramaggiore','Лизон Прамаджоре'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Lugana - Veneto','Лугана Венето'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Merlara','Мерлара'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Montello Rosso','Монтелло Россо'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Montello - Colli Asolani','Монтелло - Колли Азолани'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Piave','Пиаве'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Piave Malanotte','Пиаве Маланотте'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Prosecco','Просекко'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Asolo Prosecco','Азоло Просекко'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Prosecco di Conegliano-Valdobbiadene','Просекко ди Конельяно - Вальдобьядене'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Riviera del Brenta','Ривьера дель Брента'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Soave','Соаве'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Recioto di Soave','Речото ди Соаве'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Soave Superiore','Соаве Супериоре'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Recioto della Valpolicella','Речото делла Вальполичелла'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Valpolicella Ripasso','Вальполичелла Рипассо'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Valpolicella','Вальполичелла'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Veneto','Венето'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Venezia','Венеция'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Vicenza','Виченца'),
array('Italy','Италия','Veneto','Венето','Veneto','Венето','Trevenezie','Тревенцие'),
array('Italy','Италия','Basilicata','Базиликата','Basilicata','Базиликата','Aglianico del Vulture','Альянико дель Вультуре'),
array('Italy','Италия','Basilicata','Базиликата','Basilicata','Базиликата','Aglianico del Vulture Superiore','Альянико дель Вультуре Супериоре'),
array('Italy','Италия','Basilicata','Базиликата','Basilicata','Базиликата','Basilicata','Базиликата'),
array('Italy','Италия','Basilicata','Базиликата','Basilicata','Базиликата','Grottino di Roccanova','Гроттино ди Рокканова'),
array('Italy','Италия','Basilicata','Базиликата','Basilicata','Базиликата','Matera','Матера'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Bivongi','Бивонджи'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Calabria','Калабрия'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Ciro','Чиро'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Greco di Bianco','Греко ди Бьянко'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Lamezia','Ламеция'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Melissa','Мелисса'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Sant\'Anna di Isola Capo Rizzuto','Сант’Анна Изола Ди Капо Риццуто'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Savuto','Савуто'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Scavigna','Скавинья'),
array('Italy','Италия','Calabria','Калабрия','Calabria','Калабрия','Terre di Cosenza','Терре ди Козенца'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Aglianico del Taburno','Альянико дель Табурно'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Aversa','Аверса'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Beneventano','Беневентано'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Campania','Кампания'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Campi Flegrei','Кампи Флегреи'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Capri','Капри'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Casavecchia di Pontelatone','Казавеккиа ди Понтелатоне'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Castel San Lorenzo','Кастель Сан-Лоренцо'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Cilento','Чиленто'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Colli di Salerno','Колли ди Салерно'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Costa d\'Amalfi','Коста д\'Амальфи'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Falanghina del Sannio','Фалангина дель Саннио'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Falerno del Massico','Фалерно дель Массико'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Fiano di Avellino','Фиано ди Авеллино'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Galluccio','Галлуччо'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Greco di Tufo','Греко ди Туффо'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Irpinia','Ирпиния'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Ischia','Искья'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Penisola Sorrentina','Пенизола Соррентина'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Sannio','Саннио'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Sant\'Agata dei Goti','Сант\'Агата-де-Готи'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Taburno','Табурно'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Taurasi','Таурази'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Terre del Volturno','Терре дель Вольтурно'),
array('Italy','Италия','Campania','Кампания','Campania','Кампания','Vesuvio','Везувио'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Aleatico di Puglia','Алеатико ди Пулья'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Alezio','Алецио'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Brindisi','Бриндизи'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Barletta','Барлетта'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Cacc\'e Mmitte di Lucera','Качч\'е Ммитте ди Лучера'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Castel del Monte','Кастель дель Монте'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Colline Joniche Tarantine','Коллине Йонике Тарантине'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Copertino','Копертино'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Castel del Monte Bombino Nero','Кастель дель Монте Бомбино Неро'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Castel del Monte Nero di Troia Riserva','Кастель дель Монте Неро ди Троя'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Castel del Monte Rosso Riserva','Кастель дель Монте Россо Ризерва'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Daunia','Дауния'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Galatina','Галатина'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Gioia del Colle','Джоя дель Колле'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Gravina','Гравина'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Leverano','Леверано'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Lizzano','Лиццано'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Locorotondo','Локоротондо'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Martina','Мартина'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Matino','Матино'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Moscato di Trani','Москато ди Трани'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Murgia','Мурджа'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Nardo','Нардо'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Orta Nova','Орта Нова'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Ostuni','Остуни'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Primitivo di Manduria','Примитиво ди Мандурия'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Puglia','Апулия'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Rosso Barletta','Россо Барлетта'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Rosso di Cerignola','Россо ди Чериньола'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Salice Salentino','Саличе Салентино'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Salento','Саленто'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','San Severo','Сан Северо'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Squinzano','Сквинцано'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Tavoliere','Таволиере'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Tarantino','Тарантино'),
array('Italy','Италия','Puglia','Апулия','Puglia','Апулия','Valle d\'Itria','Валле д\'Итрия'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Alghero','Альгеро'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Arborea','Арбория'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Barbagia','Barbagia'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Cagliari','Кальяри'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Campidano di Terralba','Кампидано ди Терральба'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Cannonau di Sardegna','Каннонау ди Сардиния'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Carignano del Sulcis','Кариньяно дель Сульчис'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Giro di Cagliari','Джиро ди Кальяри'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Isola dei Nuraghi','Изола дей Нураги'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Malvasia di Bosa','Мальвазия ди Боза'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Mandrolisai','Мандролизай'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Marmilla','Мармилла'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Monica di Sardegna','Моника ди Сардиния'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Moscato di Sardegna','Москато ди Сардиния'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Moscato di Sorso-Sennori','Москато ди Сорсо-Сеннори'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Nasco di Cagliari','Наско ди Кальяри'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Nuragus di Cagliari','Нурагус ди Кальяри'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Ogliastra','Ольястра'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Sardegna Semidano','Сардиния Семидано'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Valle del Tirso','Валле дель Тирсо'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Vermentino di Gallura','Верментино ди Галлура'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Vermentino di Sardegna','Верментино ди Сардиния'),
array('Italy','Италия','Sardinia','Сардиния','Sardinia','Сардиния','Vernaccia di Oristano','Верначча ди Ористано'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Alcamo','Алькамо'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Cerasuolo di Vittoria','Черасуолло ди Виттория'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Contea di Sclafani','Контеа ди Склафани'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Contessa Entellina','Контесса Энтеллина'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Delia Nivolelli','Делия Ниволелли'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Eloro','Элоро'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Erice','Эриче'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Etna','Этна'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Faro','Фаро'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Malvasia delle Lipari','Мальвазия ди Липари'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Mamertino di Milazzo','Мамертино ди Милаццо'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Marsala','Марсала'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Menfi','Менфи'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Monreale','Монреале'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Moscato di Noto','Москато Ди Ното'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Moscato Passito di Pantelleria','Москато Пассито ди Пантеллерия'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Passito di Pantelleria','Пассито ди Пантеллерия'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Moscato di Siracusa','Москато ди Сиракуза'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Noto','Ното'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Riesi','Рьези'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Salaparuta','Салапарута'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Sambuca di Sicilia','Самбука ди Сицилия'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Santa Margherita di Belice','Санта Маргерита ди Беличе'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Sciacca','Шакка'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Sicilia','Сицилия'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Siracusa','Сиракуза'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Terre Siciliane','Терре Сичилиане'),
array('Italy','Италия','Sicily','Сицилия','Sicily','Сицилия','Vittoria','Виттория')
);