<form method="POST"><input type="hidden" name="action" value="edit_tasting_vintage_ranking" /><script type="string" class="dropbox-template-empty-string">...</script><table class="subcontent tasting-vintage-ranking-edit"><thead><tr class="header"><th colspan="7"><?=langTranslate('tasting', 'tasting', 'Product List',  'Product List')?></th></tr><tr><th></th><th></th><th class="name"><?=langTranslate('product','vintage','Name','Name')?></th><th><?=langTranslate('product','vintage','Volume','Volume')?></th><th class="raise-index"></th><th></th><th class="lower-index"></th></tr></thead><tbody><?php 
    foreach($vintage_ranking_list as $vintage):
?><tr><td class="index"><span><?=$vintage['index']?></span><input type="hidden" name="index[<?=$vintage['id']?>]" value="<?=$vintage['index']?>" /></td><td class="image wi-gallery"><?=$vintage['img']?'<img src="'.$vintage['img'].'" />':''?></td><td class="name"><?=htmlentities($vintage['fullname'])?><?=$vintage['isprimeur']?'<span class="primeur">'.langTranslate('tasting','vintage','En primeur', 'En primeur').'</span>':''?><?=strlen($vintage['lot'])?'<span class="lot"><label>'.langTranslate('tasting', 'vintage', 'Lot', 'Lot').'</label>'.htmlentities($vintage['lot']).'</span>':''?></td><td class="volume"><?=htmlentities($vintage['volume'])?></td><td class="raise-index"><span></span></td><td><div class="dropbox has-selected" data-custom="1"><input type="checkbox" id="ranking-index-drop-down-<?=$vintage['id']?>" /><label for="ranking-index-drop-down-<?=$vintage['id']?>"><?=$vintage['index']?></label><ul>
<?php   for($index=1;$index<=count($vintage_ranking_list);$index++):?>
    <li class="item <?=$index==$vintage['index']?'selected':''?>"><label><input type="checkbox" value="<?=$index?>" <?=$index==$vintage['index']?'checked="checked"':''?> /><span></span><?=$index?></label></li>
<?php   endfor; ?>
</ul></div></td><td class="lower-index"><span></span></td></tr><?php 
    endforeach; 
?></tbody><tfoot><tr><th colspan="7"><input type="submit" value="<?=langTranslate('product','review','Save','Save');?>" /></th></tr></tfoot></table></form>
